function Hd = bandpassfilter
%BANDPASSFILTER 이산시간 필터 객체를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 20-Aug-2020 15:28:56

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 20;  % Sampling Frequency

Fstop1 = 0.23333333333;  % First Stopband Frequency
Fpass1 = 0.33333333333;  % First Passband Frequency
Fpass2 = 0.61666666667;  % Second Passband Frequency
Fstop2 = 0.66666666667;  % Second Stopband Frequency
Astop1 = 60;             % First Stopband Attenuation (dB)
Apass  = 1;              % Passband Ripple (dB)
Astop2 = 80;             % Second Stopband Attenuation (dB)
match  = 'passband';     % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
